### ISSUE TITLE
OCN接続につきまして

### ISSUE THREAD

**Issue by site-u2023** [ikm-san/openwrt#1]
こんにちは
早速ですが、
以下の値が不整合でした
具体的には、この値で動きました
```sh
wanmap.ip4prefixlen='20'
wanmap.ip6prefix	末尾に” : ”一つ足りず
wanmap.ip6prefixlen='38'
wanmap.ealen='18'
wanmap.psidlen='6'
wanmap.offset='6'
```
尚、nuro map-e　は以下で動作するようです⁉
※環境が無い為、検証できず
https://github.com/site-u2023/config-software/blob/main/map-e-nuro.sh

LuCiの組み込み方の勉強になりました
参考にさせて頂きます！

**Comment by ikm-san** [comment]
ご確認いただいてありがとうございます。
まさか師匠から連絡頂けるとは思っていませんでしたのでびっくりです。
いつも勉強させてもらっています。

もうすぐ回線環境をOCNバーチャルコネクトに切り替えるので、
そこでバグとりと、値計算の方法見直しかけます。計算せずテーブル化も検討しています。

また、Staticなインターフェースで処理している方と、DHCPで処理している方と流派が分かれているので、
こちらも検証しようと思います。

Nuroに関しても教えていただきありがとうございます。ここにきてまた増えるのですね・・・。

これからもよろしくお願いします。
